Repository BuildForSDG/Team-075-ERS, pull requests merged in 2020-06, with the labels that each got.

#70 Ch response team
  src/pages/googleMap/googleMap.css
  src/pages/googleMap/googleMap.jsx
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
Labels: bug

#75 bug: Show user profile and victim info
  src/components/card/card.jsx
  src/components/modal/MessageModal.js
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
  src/pages/userProfile/userProfile.component.jsx
Labels: bug

#77 Ft call dialler
  src/components/card/card.jsx
  src/components/modal/MessageModal.js
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
  src/pages/userProfile/userProfile.component.jsx
Labels: enhancement

#81 Ft response team signup
  src/app.js
  src/components/responseUnitSignUp/SignUp.jsx
  src/pages/signup/sign-up.css
Labels: enhancement

#82 Ch style fix
  src/assets/images/rings.svg
  src/components/nav-bar/Navbar.jsx
  src/components/nav-bar/navbar.css
  src/index.css
  src/pages/homepage/home-page.css
  src/pages/login/Login.jsx
  src/pages/signup/SignUp.jsx
  src/pages/signup/sign-up.css
  src/pages/userProfile/user-profile.css
Labels: bug

#85 Ft response team login
  src/app.js
  src/pages/responseUnit/login/Login.jsx
  src/pages/signup/sign-up.css
Labels: enhancement

#87 Ft dashboard component
  src/app.js
  src/assets/images/correct.svg
  src/assets/images/customer-service.svg
  src/assets/images/pin.svg
  src/assets/images/wait.svg
  src/components/dashboard/Dashboard.jsx
  src/components/dashboard/dashboard.css
  src/components/nav-bar/Navbar.jsx
  src/components/nav-bar/navbar.css
  src/components/sidebar/Sidebar.jsx
  src/components/sidebar/sidebar.css
  src/pages/adminPanel/Admin.jsx
  src/pages/adminPanel/admin.css
  src/pages/signup/sign-up.css
Labels: enhancement

#93 Ch json update
  src/app.js
  src/components/modal/Modal.jsx
  src/components/nav-bar/Navbar.jsx
  src/components/toast/toast.jsx
  src/pages/homepage/HomePage.jsx
  src/pages/updateProfile/UpdateProfile.jsx
  src/pages/userProfile/userProfile.component.jsx
  src/redux/modal/modal.actions.js
  src/redux/modal/modal.constants.js
  src/redux/modal/modal.reducer.js
  src/redux/report/report.actions.js
  src/redux/report/report.reducer.js
Labels: enhancement

#105 Fix stylings
  package-lock.json
  src/components/card/card.css
  src/components/modal/modal.css
  src/pages/homepage/HomePage.jsx
  src/pages/responseUnit/login/Login.jsx
  src/pages/signup/SignUp.jsx
  src/pages/signup/sign-up.css
Labels: enhancement

#118 chore: updated report accident page
  src/pages/reportAccidentPage/ReportAccident.jsx
  src/redux/report/report.actions.js
Labels: bug

#119 Ch heroku update
  src/components/nav-bar/Navbar.jsx
  src/pages/googleMap/googleMap.jsx
  src/pages/homepage/HomePage.jsx
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
Labels: enhancement

#123 Ch heroku update
  src/app.js
  src/components/nav-bar/Navbar.jsx
  src/components/sidebar/Sidebar.jsx
  src/pages/googleMap/googleMap.jsx
  src/redux/root-reducer.js
Labels: enhancement

#128 Rf response homepage
  src/app.js
  src/components/dashboard/Dashboard.jsx
  src/components/logout/Logout.jsx
  src/components/nav-bar/Navbar.jsx
  src/components/show-victim-info/showVictimInfo.jsx
  src/pages/googleMap/googleMap.jsx
  src/pages/homepage/HomePage.jsx
  src/pages/login/Login.jsx
  src/pages/reportAccidentPage/ReportAccident.jsx
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
  src/pushSubscription.js
  src/redux/response/response.actions.js
  src/redux/response/response.reducer.js
  src/redux/root-reducer.js
  src/redux/user/user.actions.js
  src/redux/user/user.constants.js
  src/redux/user/user.reducer.js
Labels: enhancement

#131 Ch style fix
  src/components/card/card.css
  src/components/dashboard/dashboard.css
  src/components/login-status/status.css
  src/components/modal/modal.css
  src/components/responseUnitSignUp/ResponseUnitSignUp.jsx
  src/components/responseUnits/response-units.jsx
  src/components/show-victim-info/show-victim-info.css
  src/components/show-victim-info/showVictimInfo.jsx
  src/components/sidebar/sidebar.css
  src/pages/adminPanel/admin.css
  src/pages/googleMap/googleMap.css
  src/pages/responseUnit/login/Login.jsx
  src/pages/responseUnitHomePage/response-unit-homepage.css
  src/pages/signup/sign-up.css
  src/redux/subscription/subscription.constants.js
Labels: enhancement

#132 feat: Update victim status
  src/components/card/card.css
  src/components/card/card.jsx
  src/components/dashboard/Dashboard.jsx
  src/components/show-victim-info/showVictimInfo.jsx
  src/pages/googleMap/googleMap.jsx
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
  src/redux/modal/modal.actions.js
  src/redux/modal/modal.constants.js
  src/redux/modal/modal.reducer.js
  src/redux/response/response.actions.js
  src/redux/response/response.constants.js
  src/redux/response/response.reducer.js
Labels: enhancement

#134 Bug fix
  src/components/show-victim-info/showVictimInfo.jsx
  src/redux/response/response.actions.js
  src/redux/user/user.actions.js
Labels: bug

#137 fix: cors issue logging in with socials
  package-lock.json
  package.json
  src/app.js
  src/components/show-victim-info/showVictimInfo.jsx
  src/index.js
  src/pages/homepage/HomePage.jsx
  src/pages/login/Login.jsx
  src/pushSubscription.js
  src/redux/user/user.actions.js
  src/redux/user/user.reducer.js
Labels: bug

#138 feat: Send response unit location every 30sec
  package-lock.json
  src/app.js
  src/pages/adminPanel/Admin.jsx
  src/pages/responseUnitHomePage/responseUnitHomePage.jsx
  src/redux/response/response.actions.js
  src/redux/response/response.constants.js
  src/redux/response/response.reducer.js
  yarn.lock
Labels: enhancement

#140 Bg bug fix
  src/app.js
  src/components/nav-bar/Navbar.jsx
  src/pages/homepage/HomePage.jsx
Labels: bug

#142 Chore: Display messages from API
  src/App.css
  src/app.js
  src/components/modalLogin/modal-login.jsx
  src/components/nav-bar/Navbar.jsx
  src/components/nav-bar/navbar.css
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/home-page.css
  src/pages/login/Login.jsx
  src/pages/responseUnit/login/Login.jsx
  src/pages/signup/SignUp.jsx
  src/redux/user/user.actions.js
  src/redux/user/user.constants.js
  src/redux/user/user.reducer.js
Labels: enhancement

#143 fix: dashboard and login pages
  src/app.js
  src/components/dashboard/Dashboard.jsx
  src/components/modal/modal.css
  src/pages/responseUnit/login/Login.jsx
  src/redux/response/response.actions.js
  src/redux/response/response.reducer.js
  src/redux/user/user.actions.js
Labels: bug, enhancement
